# before_install:
# - docker -v && docker-compose -v
# - sudo rm /usr/local/bin/docker-compose
# - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
# - chmod +x docker-compose
# - sudo mv docker-compose /usr/local/bin
# - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
# - chmod +x ./kubectl
# - sudo mv ./kubectl /usr/local/bin/kubectl
# - if [ ! -d $HOME/gcloud/google-cloud-sdk ]; then
#     mkdir -p $HOME/gcloud &&
#     wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz --directory-prefix=$HOME/gcloud &&
#     cd $HOME/gcloud &&
#     tar xzf google-cloud-sdk.tar.gz &&
#     printf '\ny\n\ny\ny\n' | ./google-cloud-sdk/install.sh &&
#     cd $TRAVIS_BUILD_DIR;
#   fi
# - gcloud -q components update
# - if [ -a ${KEY_FILE} ]; then
#     gcloud -q auth activate-service-account --key-file ${KEY_FILE};
#   fi
# install:
# - docker-compose -f course-03/exercises/udacity-c3-deployment/docker/docker-compose-build.yaml build --parallel
# - docker login -u ${DOCKER_USENAME} -p ${DOCKER_PASSWORD}
# - docker push lasz/udacity-restapi-feed:v0.1.2
# - docker push lasz/udacity-restapi-user:v0.1.2
# - docker push lasz/udacity-frontend
# - docker push lasz/reverse-proxy:v0.1.0
# - gcloud config set project ${PROJECT_ID}
# - gcloud container clusters get-credentials ${K8s_CLUSTER} --zone ${ZONE} --project ${PROJECT_ID}
# - gcloud auth configure-docker
# - kubectl apply -f ./course-03/exercises/udacity-c3-deployment/k8s/aws-secret.yaml
# - kubectl apply -f ./course-03/exercises/udacity-c3-deployment/k8s/env-configmap.yaml
# - kubectl apply -f ./course-03/exercises/udacity-c3-deployment/k8s/env-secret.yaml
# - kubectl apply -f ./course-03/exercises/udacity-c3-deployment/k8s/backend-feed-service.yaml
# - kubectl apply -f ./course-03/exercises/udacity-c3-deployment/k8s/backend-user-service.yaml
# - kubectl apply -f ./course-03/exercises/udacity-c3-deployment/k8s/frontend-service.yaml
# - kubectl apply -f ./course-03/exercises/udacity-c3-deployment/k8s/reverseproxy-service.yaml
# - kubectl apply -f ./course-03/exercises/udacity-c3-deployment/k8s/backend-feed-deployment.yaml
# - kubectl apply -f ./course-03/exercises/udacity-c3-deployment/k8s/backend-user-deployment.yaml
# - kubectl apply -f ./course-03/exercises/udacity-c3-deployment/k8s/frontend-deployment.yaml
# - kubectl apply -f ./course-03/exercises/udacity-c3-deployment/k8s/reverseproxy-deployment.yaml 

language: minimal
branches:
  only:
  - dev

cache:
  directories:
  - "$HOME/google-cloud-sdk"

services: docker

env:
  - DOCKER_COMPOSE_VERSION=1.23.2
  - KEY_FILE=udagram-kubernetes-b9b36bbe56f6.json
  - PROJECT_ID=udagram-kubernetes
  - K8s_CLUSTER=udagram-cluster
  - ZONE=us-west1-a
  # global:
  # - secure: nxOZeYV0ir3FHRsL9Pw5Ee0v5NOi6I899inki1DD10Pu+NpHNEYn0oY2Qm/tLZaVnS3IYS2x5/gyfT2OVHLjOJlHVIyypAoFtc6G2OU49khZy8idwwJ3wbD8KJr8ZvopuIo4ZME4RSlWo5vM4p8svxP/n2fSEBRrgbvm7ddJnplR3rWlTHxKAfWVZ+r/76jdNtAcqtknxn7340QhRdk7SZvwZ1uRRxDiqwNvc7jcWDr/+Aqz98Z4nZIJuDHggUi0CS/hiQi6zFW9k0fKSvhR5FWOMxkE1FRMk+6NQ4xGku83jKApr0Lsb2uHlX2IEJnbc584tGcQ6ONaks268YaRFHrboBAZiMEC3ZOPWJqWLwo6YOKB1td5TAiG/LBw6RuuUHOYFGdkSqP7BGJG2QIpuvK4GbLSrduxhe/KIDOHF1KlVLdoXMTqYOn8q/VPhPryqSYZe0qlMAacjUiN0M6EbIS49vQq/cjCLuQkutBVO2bMAWzowgLzzSlkRL3VZssm3BRKpFAiS/HKX853BvF94bnwpqA60S/M4liAf7N2bsBCeS8o1Xp8HWA4JIDaOnI1rwy/jnO7G8EI903dKdfFoqIWBbpEH89UX33Xn3ziwK1HNgSjYqt/P6XZLjeeEA3rGcE7GhXfNBzFbQHQKRIPU7SLaLxoNGt/QdeiOl/W+4I=
  # - secure: H5I/4O3IujomATFR8qSZIdh8CrY2drH3+EqszLiBkEoJLCLz14dz33Sdd4L6pAUAVWcPTQPffL76DtpV4Mllv+RNLz5bDpjWYswFzZI0XmNtsL2uHndwqqv/rMmChnLJyZ266XO1FCC6XPHtAEevI+N2llnq/a8ZMA25SijLrBH1XWkeB6TQZfmQCAvhEkEOG/MQ1fvdT+G5JGT7mzRE34aRkP92pqOJMMmkut2gNQPPsrXayA53j9M72wQzzwlYbjpkAxQtnaTffJg/3th0NErs65WJEs0TwgXqXYljZ9mWBJRuVxKILhoc/O8QWrwEAbpyqc3Gm1Zq2qXymvwTthPFEYva1eCYxe4ruUdepPb3r3PQDpsB440EuwI9suD5cDnPNPxzplo4nFFrgctnYBONTokDiT0XCsTbHMWgEcQ0a/39i/qHRV4vn4+QwKdX1RVHNbkQuxyMk0f5GXQxzbU6nWHCYifnExG7v/jjSVvq0W7r7cHZBQL7uyIUhjEn4FlMapvsJcERlq9xa1pr4mIZ/mQDUlrqPIeiygxxoBaP+EwB77L9V6cSP1A37XKS0kEIKwq7JI/C2SzIJ5aO9ZQeu7kwoRJ+l4pnPOwXP0ErAbdyypBtRiS6JuE9d5x5Bn3UILIuwrfhgcAOzYSUx4VCe0xPR7PNMwhlNS2Wf/E=
  # - secure: iWNnQVATC0refT1LKP/B0C9T2Sseg/hOclhRnM5NVXHl7JLezEzOOiNw4pZi2Qmr8BPYC/FyDbNUPHfit/3kuva1cquHv5kBpJOl8yPIkBSfNJ7ecMw67n+op5n6BvCvht9fQOxUbMPYcE4PiVcZKXwJPVD473RAhPMHaduJqdtPNr+zYG9tO/eFdtYpqS5R3v/w1CbkBJmv/pK1gloibyKXZBFs4hrK4rJh3W1S82gDuXOsq0kYPzJn3cfzaxQ0jVxSUZXF5bMny1Dhs4T+2xgtfPGs5ia3AvplRaRryH/gDxfjKu/ARwKOBM6FNGKuZnNrjD8tCrfoPygK8TkoLqdw7NPVXxxY59yFoB0+XK00EugtpzIHad4vL1HIi7jqZrDRQQAN0ILnoqZZSA3Gi+cQ3Q/kf+g/REr5XkywSgucggRitKTCNIc/UEF/bQhbXMQhiQ8wiHD5VHhFrVkuzK5WY8x+EDFYoi1hnLZ18YN6aezhlOxDRqzbcyMURdivia7gNmJCnRXPMigLxujAZD21/O1JwUdG9nSDW6of2zcaIhbyup256+TQOxp2jwsciAsVuosKc5fHvHoUvI2H0FWJzfPT5ZbFPiHs4obTST3pz9RtNvTG0fGOCXBSEppSqNDmS4SX1k/E8U4gqJyUxvEIMPQiNWmeSNWyvxp/Me8=

before_install:
  - docker -v && docker-compose -v
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl

# - if [ ! -d $HOME/gcloud/google-cloud-sdk ]; then
#     mkdir -p $HOME/gcloud &&
#     wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz --directory-prefix=$HOME/gcloud &&
#     cd $HOME/gcloud &&
#     tar xzf google-cloud-sdk.tar.gz &&
#     printf '\ny\n\ny\ny\n' | ./google-cloud-sdk/install.sh &&
#     cd $TRAVIS_BUILD_DIR;
#   fi

- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then 
    rm -rf "$HOME/google-cloud-sdk"
    curl https://sdk.cloud.google.com | bash > /dev/null
  fi

install:
  - docker-compose -f course-03/exercises/udacity-c3-deployment/docker/docker-compose-build.yaml build --parallel 