apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: backend-user
  name: backend-user
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      service: backend-user
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: backend-user
    spec:
      containers:
      - env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              key: URL
              name: env-config
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              key: JWT_SECRET
              name: env-config
        - name: POSTGRESS_DATABASE
          valueFrom:
            configMapKeyRef:
              key: POSTGRESS_DATABASE
              name: env-config
        - name: POSTGRESS_HOST
          valueFrom:
            configMapKeyRef:
              key: POSTGRESS_HOST
              name: env-config
        - name: POSTGRESS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRESS_PASSWORD
              name: env-secret
        - name: POSTGRESS_USERNAME
          valueFrom:
            secretKeyRef:
              key: POSTGRESS_USERNAME
              name: env-secret
        image: lasz/udacity-restapi-user
        imagePullPolicy: Always
        name: backend-user
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        readinessProbe:
          httpGet:
             path: /
             port: 8080
             initialDelaySeconds: 5
             periodSeconds: 5
             successThreshold: 1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
