apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  selector:
    service: backend-user
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  # - name: "postges"
  #   port: 5432
  #   targetPort: 5432