apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    service: frontend
spec:
  selector:
    matchLabels:
      service: frontend
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        service: frontend
        api: external        
    spec:
      containers:
      - image: lasz/udacity-frontend:v0.1.1
        name: frontend
        imagePullPolicy: Always      
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        ports:
        - containerPort: 80 
        readinessProbe:
          httpGet:
            path: /
            port: 80 
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
      restartPolicy: Always
