# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   creationTimestamp: null
#   labels:
#     service: frontend
#   name: frontend
# spec:
#   progressDeadlineSeconds: 2147483647
#   replicas: 2
#   revisionHistoryLimit: 2147483647
#   selector:
#     matchLabels:
#       api: external
#       service: frontend
#   strategy:
#     rollingUpdate:
#       maxSurge: 1
#       maxUnavailable: 1
#     type: RollingUpdate
#   template:
#     metadata:
#       creationTimestamp: null
#       labels:
#         api: external
#         service: frontend
#     spec:
#       containers:
#       - image: lasz/udacity-frontend
#         imagePullPolicy: Always
#         name: frontend
#         ports:
#         - containerPort: 80
#           protocol: TCP
#         resources:
#           limits:
#             cpu: 500m
#             memory: 1Gi
#           requests:
#             cpu: 250m
#             memory: 64Mi
#         terminationMessagePath: /dev/termination-log
#         terminationMessagePolicy: File
#         readinessProbe:
#           httpGet:
#              path: /
#              port: 8080
#              initialDelaySeconds: 5
#              periodSeconds: 5
#              successThreshold: 1
#       dnsPolicy: ClusterFirst
#       restartPolicy: Always
#       schedulerName: default-scheduler
#       securityContext: {}
#       terminationGracePeriodSeconds: 30

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  selector:
    matchLabels:
      service: frontend
  replicas: 1
  template:
    metadata:
      labels:
        service: frontend
        api: external        
    spec:
      containers:
<<<<<<< HEAD
<<<<<<< HEAD
      - image: lasz/udacity-frontend:local
=======
      - image: lasz/udacity-frontend
        imagePullPolicy: Always
>>>>>>> release/1.0.2
=======
      - image: lasz/udacity-frontend:v0.1.0
>>>>>>> release/1.0.3
        name: frontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                
      restartPolicy: Always