apiVersion: v1
kind: Service
metadata:
  labels:
    service: postgres
  name: postgres
spec:
  type: LoadBalancer   
  selector:
    service: backend-feed
  ports:
  - name: "postges"
    port: 5432
    targetPort: 5432