apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  selector:
    matchLabels:
      service: backend-user
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: backend-user
    spec:
      containers:
        image: lasz/udacity-restapi-user
        name: backend-user
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 1Gi
      - env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              key: URL
              name: env-config
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              key: JWT_SECRET
              name: env-config
        - name: POSTGRESS_DATABASE
          valueFrom:
            configMapKeyRef:
              key: POSTGRESS_DATABASE
              name: env-config
        - name: POSTGRESS_HOST
          valueFrom:
            configMapKeyRef:
              key: POSTGRESS_HOST
              name: env-config
        - name: POSTGRESS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRESS_PASSWORD
              name: env-secret
        - name: POSTGRESS_USERNAME
          valueFrom:
            secretKeyRef:
              key: POSTGRESS_USERNAME
              name: env-secret
      restartPolicy: Always
