apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  selector:
    matchLabels:
      service: frontend
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: frontend
        api: external        
    spec:
      containers:
      - image: lasz/udacity-frontend:v0.1.1
        name: frontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "250m"                
      restartPolicy: Always